### ISSUE TITLE
List of Content

### ISSUE THREAD

**Issue by Moonded** [WolvenKit/wolvenkit-www#22]
I'm listening here whatever needs to be done or is already done. If you want something to be added, leave a comment.

---
### Front end
- [x] Index Page
  - [x] Start Projects
  - [x] Blog Posts
  - [x] Discord (Animated Wumpus)
  - [x] Github (Animated Octocat)
- [ ] Team page
  - [ ] All Team Members (Still missing some, and their descriptions, etc)
- [x] Wiki
  - [x] Working Wiki
- [ ] Projects
  - [ ] All projects listed
- [ ] Zines page
- [ ] NativeDB
- [x] Doxygen-html (look discord pins) (temporarily done on webserver)
- [ ] Language translation [see here for discussion](https://github.com/WolvenKit/wolvenkit-www/issues/32)

### Backend
- [x] Backend CMS [see here for discussion](https://github.com/WolvenKit/wolvenkit-www/issues/19)

**Comment by Moonded** [comment]
Add fuzzos doxygen-html

**Comment by SpookieCL** [comment]
Added missing team members in team page. #39
