### ISSUE TITLE
i18n support for meta tags and alt tags

### ISSUE THREAD

**Issue by zSoulweaver** [WolvenKit/wolvenkit-www#29]
Didn't get around to this with my initial PR. Might work on it later, but I'll pop this issue up to track it in anybody wants to do it.

Currently the i18n is only enabled for normal text fields, support for alt tags and the html meta tags should be added as well.

**Comment by Nats-ji** [comment]
Also, can we add author and translator to blog metadata? and show them on the blog page along with the post date.
