### ISSUE TITLE
i18n Status

### ISSUE THREAD

**Issue by Akiway** [WolvenKit/wolvenkit-www#32]
### List of all the languages the site has been translated into and their translators

- [x] English
- [x] French (Akiway)
- [x] Simplified Chinese (Nats-ji)
- [x] Japanese (Nats-ji)
- [x] Spanish (Spookie)
- [x] Turkish (DerinHalil)
- [ ] German
- [ ] Russian

**Comment by SpookieCL** [comment]
Spanish has been added #36
