### ISSUE TITLE
Bug fixing

### ISSUE THREAD

**Issue by Moonded** [WolvenKit/wolvenkit-www#33]
### Bugs that need to be fixed

General:
- [x] Discord mascot disappearing on language change (reappearing on reload) 
- [x] Not all team members are showing

France site:
- [ ] Team member Tags (translate?)
- [x] Blog post header aint translated all
- [x] `https://redmodding.org/fr/blog/2020-12-17-cyberpunk-update-no1` Picture resize aint working (desktop AND mobile)
- [x]  Chinese in Chinese aint inline (language picker)

Chinese:
- [ ] Team member Tags (translate?)

**Comment by Moonded** [comment]
ive fixed the image real quick, as it was a simple line fix

**Comment by Moonded** [comment]
corrected the mascot bug

**Comment by zSoulweaver** [comment]
Most of the layout bugs that came from the i18n PR I've fixed in #31. 

Same for the image fixes.

**Comment by Nats-ji** [comment]
> * Team member Tags (translate?)

wdym

**Comment by Akiway** [comment]
New issue: not all team members are showing.

Only those in the content/team folder are showing, the content/teamMember folder is being ignored.

**Comment by kpracuk** [comment]
I'll take a look into it.
I've created separate issue for it
